# Generated by Django 4.2.6 on 2023-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='time_end',
            field=models.DateField(verbose_name='время конца рассылки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='time_start',
            field=models.DateField(verbose_name='время начала рассылки'),
        ),
    ]
