# Generated by Django 4.2.6 on 2023-11-09 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='clients',
            field=models.ManyToManyField(to='mailings.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='тема письма'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='CREATED', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время конца рассылки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
